import type { HttpStatusMetadata } from '../core/types.js';

export const CloudflareStatus = {
  WEB_SERVER_RETURNED_UNKNOWN_ERROR: 520,
  WEB_SERVER_IS_DOWN: 521,
  CONNECTION_TIMED_OUT: 522,
  ORIGIN_IS_UNREACHABLE: 523,
  TIMEOUT_OCCURRED: 524,
  SSL_HANDSHAKE_FAILED: 525,
  INVALID_SSL_CERTIFICATE: 526,
  RAILGUN_ERROR: 527,
  ORIGIN_DNS_ERROR: 530,
} as const;

export type CloudflareStatusCode = (typeof CloudflareStatus)[keyof typeof CloudflareStatus];
export type CloudflareStatusName = keyof typeof CloudflareStatus;

const CF_5XX_BASE =
  'https://developers.cloudflare.com/support/troubleshooting/http-status-codes/5xx-errors/';

export const CloudflareRegistry: Readonly<Record<CloudflareStatusCode, HttpStatusMetadata>> = {
  520: {
    code: 520,
    phrase: 'Web Server Returned an Unknown Error',
    category: 'Vendor Extension',
    source: 'Cloudflare',
    rfc: null,
    specUrl: `${CF_5XX_BASE}#error-520-web-server-returns-an-unknown-error`,
    description:
      'The origin server returned an empty, unknown, or unexpected response to Cloudflare.',
    expectsEmptyBody: false,
    isCacheable: false,
    requiresAuth: false,
    safeForMethods: 'all',
    relatedHeaders: [],
    aliases: [],
    deprecated: false,
    guidance: {
      isRetryable: true,
      retryStrategy: 'exponential-backoff',
      agentAction: 'Retry; if persistent, the origin is misbehaving and needs operator attention.',
      commonCauses: ['Origin crashed mid-response', 'Origin returned malformed HTTP'],
      relatedStatuses: [502],
    },
  },
  521: {
    code: 521,
    phrase: 'Web Server Is Down',
    category: 'Vendor Extension',
    source: 'Cloudflare',
    rfc: null,
    specUrl: `${CF_5XX_BASE}#error-521-web-server-is-down`,
    description:
      'The origin server refused the connection from Cloudflare. Cloudflare could not establish a TCP connection.',
    expectsEmptyBody: false,
    isCacheable: false,
    requiresAuth: false,
    safeForMethods: 'all',
    relatedHeaders: [],
    aliases: [],
    deprecated: false,
    guidance: {
      isRetryable: true,
      retryStrategy: 'exponential-backoff',
      agentAction: 'Retry; verify origin is running and not blocking Cloudflare IPs.',
      commonCauses: ['Origin down', 'Cloudflare IPs blocked at firewall'],
      relatedStatuses: [502, 503],
    },
  },
  522: {
    code: 522,
    phrase: 'Connection Timed Out',
    category: 'Vendor Extension',
    source: 'Cloudflare',
    rfc: null,
    specUrl: `${CF_5XX_BASE}#error-522-connection-timed-out`,
    description:
      'Cloudflare could not negotiate a TCP handshake with the origin server before timing out.',
    expectsEmptyBody: false,
    isCacheable: false,
    requiresAuth: false,
    safeForMethods: 'all',
    relatedHeaders: [],
    aliases: [],
    deprecated: false,
    guidance: {
      isRetryable: true,
      retryStrategy: 'exponential-backoff',
      agentAction: 'Retry; investigate origin network reachability.',
      commonCauses: ['Origin overloaded', 'Network partition between CF and origin'],
      relatedStatuses: [504],
    },
  },
  523: {
    code: 523,
    phrase: 'Origin Is Unreachable',
    category: 'Vendor Extension',
    source: 'Cloudflare',
    rfc: null,
    specUrl: `${CF_5XX_BASE}#error-523-origin-is-unreachable`,
    description:
      'Cloudflare could not reach the origin server, commonly due to a routing/BGP issue or invalid DNS record.',
    expectsEmptyBody: false,
    isCacheable: false,
    requiresAuth: false,
    safeForMethods: 'all',
    relatedHeaders: [],
    aliases: [],
    deprecated: false,
    guidance: {
      isRetryable: true,
      retryStrategy: 'exponential-backoff',
      agentAction: 'Retry; if persistent, check origin DNS and routing.',
      commonCauses: ['DNS record points to wrong IP', 'BGP routing problem'],
      relatedStatuses: [530],
    },
  },
  524: {
    code: 524,
    phrase: 'A Timeout Occurred',
    category: 'Vendor Extension',
    source: 'Cloudflare',
    rfc: null,
    specUrl: `${CF_5XX_BASE}#error-524-a-timeout-occurred`,
    description:
      'Cloudflare successfully connected and sent data to the origin, but the origin took too long to respond with an HTTP response.',
    expectsEmptyBody: false,
    isCacheable: false,
    requiresAuth: false,
    safeForMethods: 'all',
    relatedHeaders: [],
    aliases: [],
    deprecated: false,
    guidance: {
      isRetryable: true,
      retryStrategy: 'exponential-backoff',
      agentAction: 'Retry; for long-running requests, consider an async pattern (e.g., 202 + polling).',
      commonCauses: ['Long-running origin request exceeded the 100-second CF limit.'],
      relatedStatuses: [504, 408],
    },
  },
  525: {
    code: 525,
    phrase: 'SSL Handshake Failed',
    category: 'Vendor Extension',
    source: 'Cloudflare',
    rfc: null,
    specUrl: `${CF_5XX_BASE}#error-525-ssl-handshake-failed`,
    description:
      'Cloudflare could not negotiate an SSL/TLS handshake with the origin server.',
    expectsEmptyBody: false,
    isCacheable: false,
    requiresAuth: false,
    safeForMethods: 'all',
    relatedHeaders: [],
    aliases: [],
    deprecated: false,
    guidance: {
      isRetryable: false,
      retryStrategy: 'never',
      agentAction: 'Operator action: align cipher suites and TLS versions between CF and origin.',
      commonCauses: ['No common cipher suite', 'TLS version mismatch'],
      relatedStatuses: [526],
    },
  },
  526: {
    code: 526,
    phrase: 'Invalid SSL Certificate',
    category: 'Vendor Extension',
    source: 'Cloudflare',
    rfc: null,
    specUrl: `${CF_5XX_BASE}#error-526-invalid-ssl-certificate`,
    description:
      'Cloudflare could not validate the SSL certificate on the origin web server when SSL Full (strict) mode is active.',
    expectsEmptyBody: false,
    isCacheable: false,
    requiresAuth: false,
    safeForMethods: 'all',
    relatedHeaders: [],
    aliases: [],
    deprecated: false,
    guidance: {
      isRetryable: false,
      retryStrategy: 'never',
      agentAction: 'Operator action: install a valid origin certificate or relax SSL mode.',
      commonCauses: ['Expired or self-signed origin cert', 'Hostname mismatch'],
      relatedStatuses: [525],
    },
  },
  527: {
    code: 527,
    phrase: 'Railgun Error',
    category: 'Vendor Extension',
    source: 'Cloudflare',
    rfc: null,
    specUrl: `${CF_5XX_BASE}#error-527-railgun-listener-to-origin`,
    description:
      'Indicates an error connecting between Cloudflare and the origin\'s Railgun (rwengine) server.',
    expectsEmptyBody: false,
    isCacheable: false,
    requiresAuth: false,
    safeForMethods: 'all',
    relatedHeaders: [],
    aliases: [],
    deprecated: true,
    guidance: {
      isRetryable: true,
      retryStrategy: 'exponential-backoff',
      agentAction: 'Retry; Railgun is largely deprecated in favor of Argo Smart Routing.',
      commonCauses: ['Railgun listener unreachable.'],
      relatedStatuses: [],
    },
  },
  530: {
    code: 530,
    phrase: 'Origin DNS Error',
    category: 'Vendor Extension',
    source: 'Cloudflare',
    rfc: null,
    specUrl:
      'https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-1xxx-errors/',
    description:
      'A 530 response is typically returned alongside a Cloudflare 1xxx error displayed in the body, indicating an origin DNS or worker failure.',
    expectsEmptyBody: false,
    isCacheable: false,
    requiresAuth: false,
    safeForMethods: 'all',
    relatedHeaders: [],
    aliases: [],
    deprecated: false,
    guidance: {
      isRetryable: true,
      retryStrategy: 'exponential-backoff',
      agentAction: 'Inspect the body for the embedded 1xxx code; resolve DNS or Worker error.',
      commonCauses: ['Origin DNS resolution failure', 'Worker script error'],
      relatedStatuses: [523],
    },
  },
};
