import type { HttpStatusMetadata } from '../core/types.js';

export const NginxStatus = {
  NO_RESPONSE: 444,
  REQUEST_HEADER_TOO_LARGE: 494,
  SSL_CERTIFICATE_ERROR: 495,
  SSL_CERTIFICATE_REQUIRED: 496,
  HTTP_REQUEST_SENT_TO_HTTPS_PORT: 497,
  CLIENT_CLOSED_REQUEST: 499,
} as const;

export type NginxStatusCode = (typeof NginxStatus)[keyof typeof NginxStatus];
export type NginxStatusName = keyof typeof NginxStatus;

export const NginxRegistry: Readonly<Record<NginxStatusCode, HttpStatusMetadata>> = {
  444: {
    code: 444,
    phrase: 'No Response',
    category: 'Vendor Extension',
    source: 'Nginx',
    rfc: null,
    specUrl: 'https://nginx.org/en/docs/http/ngx_http_rewrite_module.html#return',
    description:
      'Nginx-specific code instructing the server to close the connection without sending any response headers (used via "return 444;").',
    expectsEmptyBody: true,
    cacheability: 'uncacheable',
    requiresAuth: false,
    safeForMethods: 'all',
    relatedHeaders: [],
    aliases: [],
    deprecated: false,
    guidance: {
      isRetryable: false,
      retryStrategy: 'never',
      agentAction: 'Treat as a deliberate drop; do not retry the same request.',
      commonCauses: ['Anti-abuse rule', 'Malformed request blocked at the edge'],
      relatedStatuses: [],
    },
  },
  494: {
    code: 494,
    phrase: 'Request Header Too Large',
    category: 'Vendor Extension',
    source: 'Nginx',
    rfc: null,
    specUrl: 'https://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers',
    description:
      'Nginx-specific code returned when the request headers exceed large_client_header_buffers.',
    expectsEmptyBody: false,
    cacheability: 'uncacheable',
    requiresAuth: false,
    safeForMethods: 'all',
    relatedHeaders: [],
    aliases: [],
    deprecated: false,
    guidance: {
      isRetryable: false,
      retryStrategy: 'never',
      agentAction: 'Trim headers/cookies and retry.',
      commonCauses: ['Oversized cookie jar', 'Long Authorization header'],
      relatedStatuses: [431],
    },
  },
  495: {
    code: 495,
    phrase: 'SSL Certificate Error',
    category: 'Vendor Extension',
    source: 'Nginx',
    rfc: null,
    specUrl: 'https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client',
    description:
      'Nginx-specific code returned when client certificate verification fails.',
    expectsEmptyBody: false,
    cacheability: 'uncacheable',
    requiresAuth: false,
    safeForMethods: 'all',
    relatedHeaders: [],
    aliases: [],
    deprecated: false,
    guidance: {
      isRetryable: false,
      retryStrategy: 'never',
      agentAction: 'Provide a valid client certificate and retry.',
      commonCauses: ['Expired or untrusted client certificate.'],
      relatedStatuses: [496],
    },
  },
  496: {
    code: 496,
    phrase: 'SSL Certificate Required',
    category: 'Vendor Extension',
    source: 'Nginx',
    rfc: null,
    specUrl: 'https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client',
    description:
      'Nginx-specific code returned when a client certificate was required but not provided.',
    expectsEmptyBody: false,
    cacheability: 'uncacheable',
    requiresAuth: true,
    safeForMethods: 'all',
    relatedHeaders: [],
    aliases: [],
    deprecated: false,
    guidance: {
      isRetryable: false,
      retryStrategy: 'never',
      agentAction: 'Attach a client certificate to the TLS connection and retry.',
      commonCauses: ['Mutual TLS endpoint reached without a client cert.'],
      relatedStatuses: [495],
    },
  },
  497: {
    code: 497,
    phrase: 'HTTP Request Sent to HTTPS Port',
    category: 'Vendor Extension',
    source: 'Nginx',
    rfc: null,
    specUrl: 'https://nginx.org/en/docs/http/ngx_http_ssl_module.html#errors',
    description:
      'Nginx-specific code returned when a plain HTTP request is sent to an HTTPS port.',
    expectsEmptyBody: false,
    cacheability: 'uncacheable',
    requiresAuth: false,
    safeForMethods: 'all',
    relatedHeaders: [],
    aliases: [],
    deprecated: false,
    guidance: {
      isRetryable: true,
      retryStrategy: 'immediate',
      agentAction: 'Reissue the request over HTTPS.',
      commonCauses: ['Client used http:// against an https-only port.'],
      relatedStatuses: [426],
    },
  },
  499: {
    code: 499,
    phrase: 'Client Closed Request',
    category: 'Vendor Extension',
    source: 'Nginx',
    rfc: null,
    specUrl: 'https://nginx.org/en/docs/http/ngx_http_core_module.html',
    description:
      'Nginx-specific code logged when the client closes the connection while the server is still processing the request.',
    expectsEmptyBody: true,
    cacheability: 'uncacheable',
    requiresAuth: false,
    safeForMethods: 'all',
    relatedHeaders: [],
    aliases: [],
    deprecated: false,
    guidance: {
      isRetryable: false,
      retryStrategy: 'never',
      agentAction: 'No action; this code is observed in access logs, not received by the client.',
      commonCauses: ['Client aborted the request', 'Network drop'],
      relatedStatuses: [408],
    },
  },
};
